### ISSUE TITLE
How To build and Run 

### ISSUE THREAD

**Issue by shangarnithi** [vmayoral/freeDDS#8]
Hi All,

Am new to DDS. Please anyone suggest me how to build and run this code in ubuntu machine. 

Thanks in advance.

**Comment by shangarnithi** [comment]
These are the errors am facing when i build the code. 

wftiotadm@wftiotadm:~/Desktop/DDS/freeDDS-master$ cmake .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wftiotadm/Desktop/DDS/freeDDS-master
wftiotadm@wftiotadm:~/Desktop/DDS/freeDDS-master$ cmake --build .
Scanning dependencies of target infrastructure
[  6%] Building C object src/infrastructure/CMakeFiles/infrastructure.dir/qos_policy.c.o
[ 12%] Linking C static library libinfrastructure.a
[ 12%] Built target infrastructure
Scanning dependencies of target domain
[ 18%] Building C object src/domain/CMakeFiles/domain.dir/domain_participant.c.o
In file included from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/data_writer.h:9:0,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/publisher.h:8,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/domain/domain_participant.h:7,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:3:
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/topic/topic.h:13:3: error: unknown type name ‘DomainParticipant’
   DomainParticipant* domain_participant;
   ^
In file included from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/publisher.h:8:0,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/domain/domain_participant.h:7,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:3:
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/data_writer.h:15:3: error: unknown type name ‘DomainParticipant’
   DomainParticipant domain_participant;  
   ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/data_writer.h:21:41: error: unknown type name ‘DomainParticipant’
 DataWriter * new_DataWriter(QoSPolicy*, DomainParticipant*, Topic*); /* Shouldn
                                         ^
In file included from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/domain/domain_participant.h:7:0,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:3:
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/publisher.h:13:3: error: unknown type name ‘DomainParticipant’
   DomainParticipant* domain_participant;
   ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/publisher.h:21:39: error: unknown type name ‘DomainParticipant’
 Publisher * new_Publisher(QoSPolicy*, DomainParticipant*);
                                       ^
In file included from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/subscription/subscriber.h:8:0,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/domain/domain_participant.h:8,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:3:
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/subscription/data_reader.h:14:3: error: unknown type name ‘DomainParticipant’
   DomainParticipant* domain_participant;
   ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/subscription/data_reader.h:20:41: error: unknown type name ‘DomainParticipant’
 DataReader * new_DataReader(QoSPolicy*, DomainParticipant*);
                                         ^
In file included from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/domain/domain_participant.h:8:0,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:3:
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/subscription/subscriber.h:14:3: error: unknown type name ‘DomainParticipant’
   DomainParticipant* domain_participant;
   ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/subscription/subscriber.h:22:41: error: unknown type name ‘DomainParticipant’
 Subscriber * new_Subscriber(QoSPolicy*, DomainParticipant*);
                                         ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c: In function ‘get_qos_DomainParticipant’:
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:26:10: error: incompatible types when returning type ‘QoSPolicy * {aka struct QoSPolicy *}’ but ‘QoSPolicy {aka struct QoSPolicy}’ was expected
   return self->qos;
          ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c: In function ‘create_publisher_DomainParticipant’:
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:31:3: error: ‘TBD’ undeclared (first use in this function)
   TBD
   ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:31:3: note: each undeclared identifier is reported only once for each function it appears in
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:32:1: error: expected ‘;’ before ‘}’ token
 }
 ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c: In function ‘create_subscriber_DomainParticipant’:
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:36:3: error: ‘TBD’ undeclared (first use in this function)
   TBD
   ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:37:1: error: expected ‘;’ before ‘}’ token
 }
 ^
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c: In function ‘create_topic_DomainParticipant’:
/home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:41:3: error: too many arguments to function ‘new_Topic’
   new_Topic("foo", qos, self);
   ^
In file included from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/data_writer.h:9:0,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/publication/publisher.h:8,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/include/domain/domain_participant.h:7,
                 from /home/wftiotadm/Desktop/DDS/freeDDS-master/src/domain/domain_participant.c:3:
/home/wftiotadm/Desktop/DDS/freeDDS-master/include/topic/topic.h:18:9: note: declared here
 Topic * new_Topic(const char *); /* Shouldn't be used */
         ^
src/domain/CMakeFiles/domain.dir/build.make:62: recipe for target 'src/domain/CMakeFiles/domain.dir/domain_participant.c.o' failed
make[2]: *** [src/domain/CMakeFiles/domain.dir/domain_participant.c.o] Error 1
CMakeFiles/Makefile2:115: recipe for target 'src/domain/CMakeFiles/domain.dir/all' failed
make[1]: *** [src/domain/CMakeFiles/domain.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vmayoral** [comment]
As pointed out in the README:

This work got moved to https://github.com/ros2/ros2_embedded_nuttx.
